name: Integration Branch

on:
  push:
    branches: 
      - integration
  pull_request:
    branches: 
      - integration

jobs:
  build-test-and-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create secrets.properties
      run: |
        echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > secrets.properties
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run unit tests
      run: ./gradlew test
      
    - name: Build APK testing
      run: ./gradlew assembleDebug
      
    - name: Upload APK to Testapp.io
      run: |
        echo "🚀 Uploading APK to Testapp.io..."
        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
        
        # Vérifier que l'APK existe
        if [ ! -f "$APK_PATH" ]; then
          echo "❌ APK not found at $APK_PATH"
          exit 1
        fi
        
        echo "📱 APK Size: $(ls -lh ${APK_PATH} | awk '{print $5}')"
        
        # Fonction de retry avec backoff
        upload_with_retry() {
          local max_attempts=3
          local attempt=1
          local delay=30
          
          while [ $attempt -le $max_attempts ]; do
            echo "🔄 Attempt $attempt/$max_attempts..."
            
            # Commande curl corrigée (une seule ligne)
            HTTP_CODE=$(curl -X POST \
              -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
              -H "User-Agent: GitHub-Actions/1.0" \
              -H "Accept: application/json" \
              -F "file=@${APK_PATH}" \
              -F "app_id=${{ secrets.APP_ID }}" \
              "https://api.testapp.io/v1/upload" \
              --max-time 300 \
              --connect-timeout 30 \
              --write-out "%{http_code}" \
              --silent \
              --output response.json)
            
            echo "📊 HTTP Response Code: $HTTP_CODE"
            
            # Vérifier le contenu de la réponse
            if [ -f response.json ]; then
              echo "📝 Response content:"
              if grep -q "<html>" response.json 2>/dev/null; then
                echo "⚠️  Received HTML error page instead of JSON"
                head -3 response.json
              else
                echo "✅ JSON Response:"
                cat response.json
              fi
              echo ""
            fi
            
            # Gestion des codes de retour
            case "$HTTP_CODE" in
              "200"|"201")
                echo "✅ APK uploaded successfully to Testapp.io!"
                echo "🔗 Access your tests at: https://portal.testapp.io/i/meYGGWaYDJ"
                return 0
                ;;
              "502"|"503"|"504"|"520"|"521"|"522"|"523"|"524")
                echo "⚠️  Server error ($HTTP_CODE) - Testapp.io may be down"
                ;;
              "401")
                echo "❌ Authentication failed - Check API_TOKEN"
                return 1
                ;;
              "403")
                echo "❌ Access forbidden - Check APP_ID"
                return 1
                ;;
              "413")
                echo "❌ File too large (consider reducing APK size)"
                return 1
                ;;
              "000"|"")
                echo "❌ Connection failed or timeout"
                ;;
              *)
                echo "❌ Unexpected HTTP code: $HTTP_CODE"
                ;;
            esac
            
            if [ $attempt -lt $max_attempts ]; then
              echo "⏳ Waiting ${delay}s before retry..."
              sleep $delay
              delay=$((delay + 30))
            fi
            
            attempt=$((attempt + 1))
          done
          
          return 1
        }
        
        # Test de connectivité simple
        echo "🌐 Checking Testapp.io connectivity..."
        if ping -c 1 api.testapp.io >/dev/null 2>&1; then
          echo "✅ Can reach api.testapp.io"
        else
          echo "⚠️  Cannot ping api.testapp.io"
        fi
        
        # Tentative d'upload
        if upload_with_retry; then
          echo "🎉 Upload successful!"
        else
          echo "💥 Upload failed - Testapp.io seems to have persistent issues"
          echo "📋 Troubleshooting steps:"
          echo "   1. Check Testapp.io status page"
          echo "   2. Verify API_TOKEN and APP_ID secrets"
          echo "   3. Manual upload: https://portal.testapp.io/i/meYGGWaYDJ"
          echo "   4. Download APK from GitHub Actions artifacts"
          
          # Pour le debugging - vérifier les secrets (sans les afficher)
          if [ -z "${{ secrets.API_TOKEN }}" ]; then
            echo "⚠️  API_TOKEN appears to be empty"
          fi
          if [ -z "${{ secrets.APP_ID }}" ]; then
            echo "⚠️  APP_ID appears to be empty"
          fi
        fi
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "[INTEGRATION] Build Status: ${{ job.status }}"
        body: |
          Integration workflow completed.
          Status: ${{ job.status }}
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          
          APK built and uploaded to Testapp.io
          UI tests ready for execution
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions <noreply@github.com>